# Generated by Django 4.2.4 on 2023-08-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='title',
            field=models.CharField(default='zero', max_length=300, verbose_name='Заголовок вакансии'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название вакансии'),
        ),
    ]
