# Generated by Django 4.2.4 on 2023-08-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_vacancy_title_alter_vacancy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='views',
            field=models.ManyToManyField(blank=True, to='vacancy.view'),
        ),
    ]
