# Generated by Django 4.2.4 on 2023-08-30 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_alter_vacancy_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='date_time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
