# Generated by Django 4.2.4 on 2023-08-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_vacancy_salary_per_hour_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary_per_hour_fixed',
            field=models.FloatField(blank=True, null=True, verbose_name='Ставка почасовая (если нет месячной) (zlot)'),
        ),
    ]
