# Generated by Django 4.2.4 on 2023-09-04 08:58

from django.db import migrations, models
import info_pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0009_alter_vacancy_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to=info_pages.models.upload_to, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=info_pages.models.upload_to, verbose_name='Файл (Если нет ссылки на YT)'),
        ),
    ]
