# Generated by Django 4.2.4 on 2023-10-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0010_alter_photo_file_alter_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True, verbose_name='Описание требования')),
            ],
            options={
                'verbose_name': 'Требование к кандидату',
                'verbose_name_plural': 'Требования к кандидатам',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.ManyToManyField(to='vacancy.requirement', verbose_name='Требования к кандидату'),
        ),
    ]
