# Generated by Django 4.2.4 on 2023-10-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0011_requirement_vacancy_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='vacancy.requirement', verbose_name='Требования к кандидату'),
        ),
    ]
