# Generated by Django 4.2.4 on 2024-03-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0013_vacancy_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='actual',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='irrelevant',
            field=models.BooleanField(default=False, verbose_name='Не актуально'),
        ),
    ]
