# Generated by Django 4.2.4 on 2024-04-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0014_remove_vacancy_actual_vacancy_irrelevant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('UAH', 'Hryvnia'), ('USD', 'US Dollar'), ('PLN', 'Polish Złoty')], max_length=5, verbose_name='Валюта')),
            ],
        ),
        migrations.RemoveField(
            model_name='hourlypaymentoption',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='default_currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('UAH', 'Hryvnia'), ('USD', 'US Dollar'), ('PLN', 'Polish Złoty')], default='PLN', max_length=5, verbose_name='Валюта по умолчанию'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='show_all_salary',
            field=models.BooleanField(default=False, verbose_name='Показывать все валюты в вакансии'),
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_per_hour_fixed',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_per_mounth_fixed',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_per_mounth_max',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_per_mounth_min',
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.UniqueConstraint(fields=('amount', 'currency'), name='unique_amount_currency'),
        ),
        migrations.AddField(
            model_name='hourlypaymentoption',
            name='hourly_rates',
            field=models.ManyToManyField(to='vacancy.salary', verbose_name='Почасовая ставка'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_per_hour_fixed',
            field=models.ManyToManyField(blank=True, related_name='salary_per_hour_fixed', to='vacancy.salary', verbose_name='Ставка почасовая (если нет месячной)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_per_mounth_fixed',
            field=models.ManyToManyField(blank=True, related_name='salary_per_mounth_fixed', to='vacancy.salary', verbose_name='Ставка месячная фиксированая (если нет минимума или максимума)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_per_mounth_max',
            field=models.ManyToManyField(blank=True, related_name='salary_per_mounth_max', to='vacancy.salary', verbose_name='Ставка месячная максимум'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_per_mounth_min',
            field=models.ManyToManyField(blank=True, related_name='salary_per_mounth_min', to='vacancy.salary', verbose_name='Ставка месячная минимум'),
        ),
    ]
