# Generated by Django 4.2.4 on 2024-04-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0015_salary_remove_hourlypaymentoption_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_az',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Название города'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Название города'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_pl',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Название города'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Название города'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Название города'),
        ),
        migrations.AddField(
            model_name='hourlypaymentoption',
            name='payment_type_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип оплаты (для студентов, ночные, испытательный и тд.)'),
        ),
        migrations.AddField(
            model_name='hourlypaymentoption',
            name='payment_type_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип оплаты (для студентов, ночные, испытательный и тд.)'),
        ),
        migrations.AddField(
            model_name='hourlypaymentoption',
            name='payment_type_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип оплаты (для студентов, ночные, испытательный и тд.)'),
        ),
        migrations.AddField(
            model_name='hourlypaymentoption',
            name='payment_type_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип оплаты (для студентов, ночные, испытательный и тд.)'),
        ),
        migrations.AddField(
            model_name='hourlypaymentoption',
            name='payment_type_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип оплаты (для студентов, ночные, испытательный и тд.)'),
        ),
        migrations.AddField(
            model_name='infolabel',
            name='benefits_az',
            field=models.CharField(max_length=512, null=True, verbose_name='Выгоды'),
        ),
        migrations.AddField(
            model_name='infolabel',
            name='benefits_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Выгоды'),
        ),
        migrations.AddField(
            model_name='infolabel',
            name='benefits_pl',
            field=models.CharField(max_length=512, null=True, verbose_name='Выгоды'),
        ),
        migrations.AddField(
            model_name='infolabel',
            name='benefits_ru',
            field=models.CharField(max_length=512, null=True, verbose_name='Выгоды'),
        ),
        migrations.AddField(
            model_name='infolabel',
            name='benefits_uk',
            field=models.CharField(max_length=512, null=True, verbose_name='Выгоды'),
        ),
        migrations.AddField(
            model_name='infolabel',
            name='house_az',
            field=models.CharField(max_length=512, null=True, verbose_name='Жилье'),
        ),
        migrations.AddField(
            model_name='infolabel',
            name='house_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Жилье'),
        ),
        migrations.AddField(
            model_name='infolabel',
            name='house_pl',
            field=models.CharField(max_length=512, null=True, verbose_name='Жилье'),
        ),
        migrations.AddField(
            model_name='infolabel',
            name='house_ru',
            field=models.CharField(max_length=512, null=True, verbose_name='Жилье'),
        ),
        migrations.AddField(
            model_name='infolabel',
            name='house_uk',
            field=models.CharField(max_length=512, null=True, verbose_name='Жилье'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='description_az',
            field=models.TextField(null=True, unique=True, verbose_name='Описание требования'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='description_en',
            field=models.TextField(null=True, unique=True, verbose_name='Описание требования'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='description_pl',
            field=models.TextField(null=True, unique=True, verbose_name='Описание требования'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='description_ru',
            field=models.TextField(null=True, unique=True, verbose_name='Описание требования'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='description_uk',
            field=models.TextField(null=True, unique=True, verbose_name='Описание требования'),
        ),
        migrations.AddField(
            model_name='sex',
            name='name_az',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='sex',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='sex',
            name='name_pl',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='sex',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='sex',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='state',
            name='name_az',
            field=models.CharField(max_length=300, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='state',
            name='name_en',
            field=models.CharField(max_length=300, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='state',
            name='name_pl',
            field=models.CharField(max_length=300, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='state',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='state',
            name='name_uk',
            field=models.CharField(max_length=300, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_az',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name_az',
            field=models.CharField(max_length=300, null=True, verbose_name='Название вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name_pl',
            field=models.CharField(max_length=300, null=True, verbose_name='Название вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name_uk',
            field=models.CharField(max_length=300, null=True, verbose_name='Название вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_az',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_pl',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_uk',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_schedule_az',
            field=models.TextField(blank=True, null=True, verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_schedule_en',
            field=models.TextField(blank=True, null=True, verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_schedule_pl',
            field=models.TextField(blank=True, null=True, verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_schedule_ru',
            field=models.TextField(blank=True, null=True, verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_schedule_uk',
            field=models.TextField(blank=True, null=True, verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='workduty',
            name='description_az',
            field=models.TextField(null=True, unique=True, verbose_name='Описание обязанности'),
        ),
        migrations.AddField(
            model_name='workduty',
            name='description_en',
            field=models.TextField(null=True, unique=True, verbose_name='Описание обязанности'),
        ),
        migrations.AddField(
            model_name='workduty',
            name='description_pl',
            field=models.TextField(null=True, unique=True, verbose_name='Описание обязанности'),
        ),
        migrations.AddField(
            model_name='workduty',
            name='description_ru',
            field=models.TextField(null=True, unique=True, verbose_name='Описание обязанности'),
        ),
        migrations.AddField(
            model_name='workduty',
            name='description_uk',
            field=models.TextField(null=True, unique=True, verbose_name='Описание обязанности'),
        ),
    ]
