# Generated by Django 4.2.4 on 2024-04-03 00:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0017_category_name_az_category_name_en_category_name_pl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlypaymentoption',
            name='hourly_rates',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='show_all_salary',
        ),
        migrations.AddField(
            model_name='hourlypaymentoption',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=10, verbose_name='Сумма'),
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_per_hour_fixed',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_per_mounth_fixed',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_per_mounth_max',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_per_mounth_min',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_per_hour_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ставка почасовая (если нет месячной)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_per_mounth_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ставка месячная фиксированая (если нет минимума или максимума)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_per_mounth_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ставка месячная максимум'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_per_mounth_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ставка месячная минимум'),
        ),
    ]
