# Generated by Django 4.2.4 on 2024-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0018_remove_hourlypaymentoption_hourly_rates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary_per_hour',
            field=models.ManyToManyField(blank=True, to='vacancy.hourlypaymentoption', verbose_name='Варианты почасовой оплаты'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_duties',
            field=models.ManyToManyField(blank=True, to='vacancy.workduty', verbose_name='Обязанности по работе'),
        ),
    ]
