# Generated by Django 4.2.4 on 2024-05-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0019_alter_vacancy_salary_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='with_experience',
            field=models.BooleanField(default=False, verbose_name='C опытом работы'),
        ),
    ]
