# Generated by Django 4.2.4 on 2024-05-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0020_vacancy_with_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='sync_id',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
