# Generated by Django 4.2.4 on 2024-08-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0021_vacancy_source_vacancy_sync_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='card_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_card_photo', to='vacancy.photo', verbose_name='Картинка карточки вакансии и обложки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Заголовок вакансии'),
        ),
    ]
