# Generated by Django 4.2.1 on 2023-05-09 10:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_vacancy_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='sex',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина'), ('МЖ', 'Мужчина/Женщина')], max_length=200, verbose_name='Пол'),
        ),
    ]
