# Generated by Django 4.2.1 on 2023-05-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_vacancy_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='sex',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='sex',
            field=models.ManyToManyField(to='main.sex', verbose_name='Пол'),
        ),
    ]
