# Generated by Django 4.2.1 on 2023-05-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_infolabels_remove_vacancy_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Город', 'verbose_name_plural': 'Список городов'},
        ),
    ]
