# Generated by Django 4.2.1 on 2023-05-17 12:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infolabels',
            name='name',
        ),
        migrations.AddField(
            model_name='infolabels',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
