# Generated by Django 4.2.1 on 2023-05-25 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_category_state_city_category_vacancy_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Индекс')),
            ],
            options={
                'verbose_name': 'Индекс',
                'verbose_name_plural': 'Индексы',
            },
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['name'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.index'),
        ),
    ]
