# Generated by Django 4.2.1 on 2023-05-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_city_category_city_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
