# Generated by Django 4.2.1 on 2023-05-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_city_state_vacancy_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
    ]
