# Generated by Django 4.2.1 on 2023-06-22 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_state_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Место работы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='index',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.index', verbose_name='Индекс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.state', verbose_name='Регион'),
            preserve_default=False,
        ),
    ]
