# Generated by Django 4.2.1 on 2023-07-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_vacancy_views_alter_view_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='date_time',
            new_name='date',
        ),
    ]
