# Generated by Django 4.2.1 on 2023-07-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_date_time_view_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='date',
            field=models.DateField(),
        ),
    ]
