# Generated by Django 4.2.1 on 2023-07-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_view_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='city',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='view',
            name='country',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='view',
            name='isp',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='view',
            name='mobile',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='view',
            name='region_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
