# Generated by Django 4.2.4 on 2023-09-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Название партнера (для удобства)'),
        ),
    ]
