# Generated by Django 4.2.4 on 2023-09-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_pages', '0003_alter_socialnetwork_link_alter_socialnetwork_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'О нас (одно поле)', 'verbose_name_plural': 'О нас (одно поле)'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Контакты (одно поле)', 'verbose_name_plural': 'Контакты (одно поле)'},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='URL встройки GMaps'),
        ),
    ]
