# Generated by Django 4.2.4 on 2023-09-04 08:58

from django.db import migrations, models
import info_pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('info_pages', '0004_alter_aboutus_options_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to=info_pages.models.upload_to, verbose_name='Файл'),
        ),
    ]
