# Generated by Django 4.2.4 on 2023-09-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_pages', '0005_alter_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Запрос для поиска в Google Maps'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address_url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='URL встройки GMaps'),
        ),
    ]
